on:
  push:
  schedule:
    - cron: "0 0 * * *"

name: Auto Update
jobs:
  auto_update_windows:
    name: Auto Update
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          iwr -useb get.scoop.sh | iex
          echo "$HOME\scoop\shims" >> $env:GITHUB_PATH
          echo "C:\ProgramData\scoop\shims" >> $env:GITHUB_PATH
          scoop install aria2
          scoop install pwsh

      - name: Update scoops
        run: |
          pwsh .\bin\checkver.ps1 -SkipUpdated -Update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Auto update"
          body: ""
