on:
  push:
  schedule:
    - cron: "0 0 * * *"

name: Auto Update
jobs:
  auto_update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Scoop-GithubActions
        uses: Ash258/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
